### ISSUE TITLE
SQLPLUS Script Runner and Credentials

### ISSUE THREAD

**Issue by martens-d** [jenkinsci/sqlplus-script-runner-plugin#55] opened 2020-10-30 16:31 UTC
If I run SqlPlus via the Script Runner I get an error:

Running defined script on username/********@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=....
...
SQL*Plus: Release 19.0.0.0.0 - Production on Fri Oct 30 16:33:05 2020
Version 19.5.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

ERROR:
ORA-01017: Benutzername/Kennwort ungultig; Anmeldung abgelehnt (username/password incorrect)

The username is correct, but I can't check the password. This must be wrong. (perhaps masked twice?) I do not use Mask Passwords Plugin.

If I use the same credentials in a pipeline it works.

withCredentials([usernamePassword(credentialsId: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', passwordVariable: 'CREDS_P', usernameVariable: 'CREDS_U')]) {
          dir("Script"){
            bat label: 'test', script: """
            echo select * from something; > test.sql
            "C:\\Program Files (x86)\\Jenkins\\workspace\\test\\Tools\\instantclient-sqlplus-windows.x64-19.5.0.0.0dbru\\sqlplus.exe" -L %CREDS_U%/"%CREDS_P%"@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=xxx)(Port=1521))(CONNECT_DATA=(SID=yyy))) @test.sql
            """
          }          
        }

**Comment by boaglio** [comment] 2020-10-31 04:54
Are you using the latest version ? 

Please also provide:

    Jenkins server Operation System;
    Jenkins version;
    Where SQLPlus Script Runner is running (local machine or slave machine);
    Slave machine Operation System (if applicable);
    Oracle Database version;
    Oracle SQL*Plus version;
    Build log with debug info enabled.

**Comment by martens-d** [comment] 2020-11-02 08:57
- Jenkins 2.249.2 running local on a Windows 10 Enterprise machine
- SQLPlus Script Runner 2.0.13 running localy at "C:\Program Files (x86)\Jenkins\workspace\test\Tools\instantclient-sqlplus-windows.x64-19.5.0.0.0dbru\"
- Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0 - Production
- SQL*Plus: Release 19.0.0.0.0 - Production on Fri Oct 30 17:23:28 2020
Version 19.5.0.0.0

**Comment by boaglio** [comment] 2020-11-02 14:52
This plugin uses Jenkins Credentials since release 2.0.0, I don't see how can go wrong, maybe it is a MS Windows issue.
Please attach build log with debug info enabled.
BTW: Mask Passwords Plugin only changes console output, so it wouldn't mess with any credentials.

**Comment by martens-d** [comment] 2020-11-03 08:56
I can't seem to get the debug infos in the logger. 
But I have the command output:

Running as SYSTEM
Baue in Arbeitsbereich C:\Program Files (x86)\Jenkins\workspace\test SQLPlus
--------------------------------------------------------------------------
Getting ORACLE_HOME...
Using custom SQL*Plus location
SQL*Plus >>> C:\Program Files (x86)\Jenkins\workspace\test\Tools\instantclient-sqlplus-windows.x64-19.5.0.0.0dbru\sqlplus.exe
[DEBUG] Global ORACLE_HOME selected
--------------------------------------------------------------------------
Using global ORACLE_HOME
 detected host = my_machine.abc.de
 slave machine ? false
--------------------------------------------------------------------------
Using ORACLE_HOME =C:\oracle\network\
--------------------------------------------------------------------------
Getting SQLPlus version
[DEBUG] ORACLE_HOME = C:\oracle\network\
[DEBUG] LD_LIBRARY_PATH = C:\oracle\network\\lib
SQL*Plus exec file = sqlplus.exe
--------------------------------------------------------------------------
[DEBUG] Statement:
C:\Program Files (x86)\Jenkins\workspace\test\Tools\instantclient-sqlplus-windows.x64-19.5.0.0.0dbru\sqlplus.exe -v  
--------------------------------------------------------------------------
[test SQLPlus] $ "C:\Program Files (x86)\Jenkins\workspace\test\Tools\instantclient-sqlplus-windows.x64-19.5.0.0.0dbru\sqlplus.exe" -v

SQL*Plus: Release 19.0.0.0.0 - Production
Version 19.5.0.0.0

Process exited with status 0
--------------------------------------------------------------------------
 detected host = my_machine.abc.de
--------------------------------------------------------------------------
Using ORACLE_HOME =C:\oracle\network\
--------------------------------------------------------------------------
Running defined script on me/********@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=xyz)(Port=1521))(CONNECT_DATA=(SID=entwpe)))
Temp script: file:/C:/WINDOWS/TEMP/temp-script-16043935189676579402737668291652.sql
--------------------------------------------------------------------------
[DEBUG] ORACLE_HOME = C:\oracle\network\
[DEBUG] LD_LIBRARY_PATH = C:\oracle\network\\lib;C:\oracle\network\
[DEBUG] found TNSNAMES.ORA on C:\oracle\network
[DEBUG] TNS_ADMIN = C:\oracle\network\
Master Work Directory = C:\Program Files (x86)\Jenkins\workspace\test SQLPlus
[DEBUG]  Statement: 
--------------------------------------------------------------------------
C:\Program Files (x86)\Jenkins\workspace\test\Tools\instantclient-sqlplus-windows.x64-19.5.0.0.0dbru\sqlplus.exe -L me/"%HIDDEN_PASSWORD%"@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=xyz)(Port=1521))(CONNECT_DATA=(SID=entwpe))) @C:\WINDOWS\TEMP\temp-script-16043935189676579402737668291652.sql  
--------------------------------------------------------------------------
 
[test SQLPlus] $ "C:\Program Files (x86)\Jenkins\workspace\test\Tools\instantclient-sqlplus-windows.x64-19.5.0.0.0dbru\sqlplus.exe" -L me/"%HIDDEN_PASSWORD%"@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=xyz)(Port=1521))(CONNECT_DATA=(SID=entwpe))) @C:\WINDOWS\TEMP\temp-script-16043935189676579402737668291652.sql

SQL*Plus: Release 19.0.0.0.0 - Production on Tue Nov 3 09:51:58 2020
Version 19.5.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

ERROR:
ORA-28000: Account ist gesperrt.


SP2-0751: Unable to connect to Oracle.  Exiting SQL*Plus
Process exited with status 1
--------------------------------------------------------------------------
Exit code: 1
--------------------------------------------------------------------------
java.lang.RuntimeException: Process exited with error
	at org.jenkinsci.plugins.sqlplus.script.runner.SQLPlusRunner.run(SQLPlusRunner.java:497)
	at org.jenkinsci.plugins.sqlplus.script.runner.SQLPlusRunnerBuilder.perform(SQLPlusRunnerBuilder.java:174)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:112)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1894)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
ERROR: Process exited with error
Publishing build last changes...
Last changes from revision f5b4c43 (current) to 2cbd733 (previous) published successfully!
Finished: FAILURE

**Comment by boaglio** [comment] 2020-11-03 12:46
This error **ORA-28000: the account is locked** only happens after a successful login,so maybe your problem is fixed.
To be sure, you can try to [unlock this account](http://www.dba-oracle.com/sf_ora_28000_the_account_is_locked.htm) and retry this job.

**Comment by martens-d** [comment] 2020-11-04 08:33
Oh, that is because I used my account to often. If I use the technical user I still get:
ERROR:
ORA-01017: Benutzername/Kennwort ungultig; Anmeldung abgelehnt (username/password wrong)

**Comment by boaglio** [comment] 2020-11-05 12:43
Ok, I reproduced this bug and it is a Jenkins core problem on Windows only, meanwhile fallback to release  2.0.12 .

**Comment by martens-d** [comment] 2020-11-05 12:46
Okay, thanks. I will use the pipeline version for now, but good to know that it is not a testup problem from my side.

Thank you for your help.

**Comment by boaglio** [comment] 2020-11-09 01:53
Fixed on release 2.0.14!  

BTW: it wasn't any Jenkins core bug, actually it was my lack of knowledge of Jenkins API =)

**Closed as completed by boaglio** 2020-11-09 01:53 UTC
